db.url=jdbc:mysql://localhost:3306/JDBCtask
db.username=root
db.password=yshu@21
db.driver=com.mysql.cj.jdbc.Driver
db.port=3306


-- property file create - DB.properties
---connect with DBproperty
-- DBproperty --> DBconn